### ISSUE TITLE
Domain suffix is same as hostname

### ISSUE THREAD

**Issue by KevinBK1998** [open-amt-cloud-toolkit/rpc-go#189]
**Describe the bug** 🪲
Domain suffix is not computed properly. For devices that do not have the FQDN as the hostname, Domain suffix is coming same as hostname.

**To Reproduce** 🪜
1. Device should have short hostname
2. Device should be in pre-provisioning state
3. Attempting AMT configuration fails with domain suffix mismatch error

**Expected behavior**
Currently rpc is considering FQDN to be same as hostname, this can be solved actual FQDN is requested like `hostname -f` in case of Linux

**Screenshots** 🖼️
<img width="885" alt="image" src="https://github.com/open-amt-cloud-toolkit/rps/assets/43042452/95aa27c5-ca55-4223-a852-619790b03c0f">

<img width="312" alt="image" src="https://github.com/open-amt-cloud-toolkit/rps/assets/43042452/4ee36cc1-cb3b-4270-a8b3-d761d790aa07">

**AMT Device (please complete the following information):** 🖥️
 - OS: Linux
 - AMT Version: 12
 - AMT Configuration Mode: Admin Control Mode
 - Network Configuration: Static IP

**Service Deployment (please complete the following information):** ⛈️
 - Deployment Type: K3s
 - Component & Version: 2.12

**Comment by bwendlandt-intel** [comment]
Hello! The team will look into this more.  Can you please provide the output of an amtinfo call on the device?
```
sudo ./rpc amtinfo
```

**Comment by knappmk** [comment]
I have a similar problem. I had already formulated a wall of text thinking it was a USB vs iPXE problem for me. Then when creating the command outputs I noticed that my "rpc version" differ.
In short in "RPC version 2.7.0" the DNS suffix still works while in "RPC version 2.10.0" and "RPC version 2.15.1" this does not work anymore.
I use the rpc-go client in SystemRescue (Arch Linux) to set up AMT. Since SystemRescue has the hostname "sysrescue" by default, I set the file "/etc/hostname" without content and set "dhcp=dhclient", as well as "hostname-mode=dhcp" in the file "/etc/NetworkManager/NetworkManager.conf" (hostname and domain prefix in SystemRescue is automatically set correctly).

Here are the command outputs:

- `hostnamectl status`
```
   Static hostname: (unset)
Transient hostname: pc12386
         Icon name: computer-desktop
           Chassis: desktop 🖥️
        Machine ID: [hidden]
           Boot ID: [hidden]
  Operating System: SystemRescue 10.01
            Kernel: Linux 6.1.30-1-lts
      Architecture: x86-64
   Hardware Vendor: MSI
    Hardware Model: [hidden]
  Firmware Version: [hidden]
     Firmware Date: [hidden]
```
- `hostname`
```
pc12386
```
- `rpc amtinfo` for (RPC Version 2.7.0)
```
Version			: 9.1.45
Build Number		: 3000
SKU			: 8
UUID			: 00000000-0000-0000-0000-000000000000
Control Mode		: pre-provisioning state
DNS Suffix		: 
DNS Suffix (OS)		: Mathematik.Uni-Marburg.DE
Hostname (OS)		: pc12386
RAS Network      	: unknown
RAS Remote Status	: not connected
RAS Trigger      	: user initiated
RAS MPS Hostname 	: 
---Wired Adapter---
DHCP Enabled 		: true
DHCP Mode    		: passive
Link Status  		: up
IP Address   		: 0.0.0.0
MAC Address  		: 44:8a:5b:a6:05:f1
---Wireless Adapter---
DHCP Enabled 		: false
DHCP Mode    		: passive
Link Status  		: down
IP Address   		: 0.0.0.0
MAC Address  		: 00:00:00:00:00:00
```
- `rpc amtinfo` for (RPC Version 2.15.1)
```
Version			: 9.1.45
Build Number		: 3000
SKU			: 8
Features		: AMT Pro 
UUID			: 00000000-0000-0000-0000-000000000000
Control Mode		: pre-provisioning state
DNS Suffix		: 
DNS Suffix (OS)		: pc12386
Hostname (OS)		: pc12386
RAS Network      	: unknown
RAS Remote Status	: not connected
RAS Trigger      	: user initiated
RAS MPS Hostname 	: 
---Wired Adapter---
DHCP Enabled 		: true
DHCP Mode    		: passive
Link Status  		: up
IP Address   		: 0.0.0.0
MAC Address  		: 44:8a:5b:a6:05:f1
---Wireless Adapter---
DHCP Enabled 		: false
DHCP Mode    		: passive
Link Status  		: down
IP Address   		: 0.0.0.0
MAC Address  		: 00:00:00:00:00:00
```

**Comment by lschnetl** [comment]
Just going to add that V2.10.0 had this issues already implemented and from what I can see there has been a shift in how the DNS names are gathered.

Sadly Linux got the short end of the stick:
https://github.com/open-amt-cloud-toolkit/rpc-go/commit/dc13b2619a00b29c26e80aabd075ad6e123399d7

**Comment by webD97** [comment]
This seems to happen if the Linux machine does not use an explicit domain in its hostname, in this case `os.Hostname()` only returns the short hostname. Interestingly, `hostname -f` on the shell is able to report a fqdn, so the information is available in some other way. The solution is probably to look into the implementation there in order to pull in the same data source.

**Comment by webD97** [comment]
I looked into the `hostname` [sources}(https://sources.debian.org/src/hostname/3.23%2Bnmu2/hostname.c/). From my understanding (I'm not that fluent in C), it basically looks up the short hostname and calls `getaddrinfo` on it. In Go this should translate to something like `os.Hostname()` -> `net.LookupHost()` -> `net.LookupAddr`. I will try this out and see if I can make a PR.
