### ISSUE TITLE
Feature request: Add option to pass customer device identifier during Activate

### ISSUE THREAD

**Issue by msbreton** [open-amt-cloud-toolkit/rpc-go#59]
Need the option to pass a customer device identifier during Activate that can later be used to identify the device (instead of UUID) for all out of band operation calls to API endpoints.

**Comment by rsdmike** [comment]
Currently you can use the `--hostname` flag to pass pretty much anything you want as an identifier, in addition can add tags post activation with the MPS API endpoint for devices as needed. Perhaps we could look at adding a `--tags` flag on RPC to provide this data during activation instead of post activation?

**Comment by rsdmike** [comment]
@matt-primrose says this should work
